kind: wasmer.io/App.v0
owner: shayanalibuilds
name: school-management
package: .
debug: false

env:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_NAME: "School Management System"
  APP_TIMEZONE: Asia/Karachi
  LOG_CHANNEL: stderr
  LOG_LEVEL: error
  SESSION_DRIVER: cookie
  CACHE_STORE: file
  QUEUE_CONNECTION: sync
  FILESYSTEM_DISK: local

capabilities:
  instaboot:
    requests:
      - path: /
      - path: /dashboard/login
