[package]
name = "shayanalibuilds/school-management"
version = "0.1.0"
description = "School management system built with Laravel, Livewire, Flux UI, and Filament."
license = "MIT"
readme = "./README.md"
repository = "https://github.com/shayanalibuilds/school-management"
entrypoint = "run"

[dependencies]
"php/php" = "^8.3"

[fs]
"/app/" = "."
"/php-config" = "wasmer"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "localhost:8080"]
env = ["PHPRC=/php-config/"]
